apiVersion: v1
kind: Service
metadata:
  name: signup-web
spec:
  ports:
    - port: 8020
      targetPort: 80
      name: signup-web
  selector:
    app: signup-web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-web
spec:
  selector:
    matchLabels:
      app: signup-web
  template:
    metadata:
      labels:
        app: signup-web
    spec:
      containers:
      - image: dwwx/signup-web:v2
        name: signup-web
        ports:
        - containerPort: 80
          name: signup-web
      nodeSelector:
        beta.kubernetes.io/os: windows
