apiVersion: v1
kind: Service
metadata:
  name: nerd-dinner-db
spec:
  ports:
    - port: 1433
  clusterIP: None
  selector:
    app: nerd-dinner-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerd-dinner-db
spec:
  selector:
    matchLabels:
      app: nerd-dinner-db
  template:
    metadata:
      labels:
        app: nerd-dinner-db
    spec:
      containers:
      - image: dockeronwindows/ch03-nerd-dinner-db:2e
        name: nerd-dinner-db
        env:
        - name: sa_password
          value: "N3rdD!Nne720^6"
        ports:
        - containerPort: 1433
          name: nerd-dinner-db
      nodeSelector:
        beta.kubernetes.io/os: windows
